selenium-hub:
  container_name: selenium-hub
  restart: always
  image: selenium/hub:2.53.0
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "4444"

selenium-node-chrome:
  container_name: selenium-node-chrome
  restart: always
  image: selenium/node-chrome:2.53.0
  net: ${CUSTOM_NETWORK_NAME}
  environment:
    SE_OPTS: "-nodeConfig /var/selenium-config/config-chrome.json"
    REMOTE_HOST: "http://selenium-node-chrome:5555"
    HUB_PORT_4444_TCP_ADDR: "selenium-hub"
    HUB_PORT_4444_TCP_PORT: "4444"

selenium-node-firefox:
  container_name: selenium-node-firefox
  restart: always
  image: selenium/node-firefox:2.53.0
  net: ${CUSTOM_NETWORK_NAME}
  environment:
    SE_OPTS: "-nodeConfig /var/selenium-config/config-firefox.json"
    REMOTE_HOST: "http://selenium-node-firefox:5555"
    HUB_PORT_4444_TCP_ADDR: "selenium-hub"
    HUB_PORT_4444_TCP_PORT: "4444"

fitnesse:
  container_name: fitnesse
  restart: always
  image: migueltanada/fitnessfirst:cyborg
  net: ${CUSTOM_NETWORK_NAME}
  ports:
    - "80:80" 
